### ISSUE TITLE
gather_cols で str_which を使う str_extract ではなく

### ISSUE THREAD

**Issue by akikirinrin** [akikirinrin/lucifer#157]
https://github.com/kikirinrin/lucifer/blame/9789efe96150b4e063dc12c7d0b41f397d3f7219/R/shapetools.R#L89-L98

**Comment by kikirinrin** [comment]
入港隻数という列を除外したいときに
gather_cols に `[^隻]` を渡すと 入港数だけは返ってきてしまう．

**Comment by akikirinrin** [comment]
解決しているように思えるので一旦close
