### ISSUE TITLE
rebelのpreview機能をオフにする

### ISSUE THREAD

**Issue by akimanabe** [akikirinrin/lucifer#190]
通常 `rebel` でファイルを読んで、`unclusterize`でクラスターを抽出する。

しかし、`rebel`でファイルを読んで、そこでクラスターを抽出せずに`dplyr`などで直接データを整形する場合、ファイルを読むと自動的に読み込んだもののpreviewが表示される。

これを例えば `preview = FALSE` などで回避できないか、という相談です。

おとなしく`readxl`使えばいいのかもしれないですが。

**Comment by akikirinrin** [comment]
ありがとう！仰る通りです！デフォルトをオフにします。
